# Kiro CLI pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.pre.zsh"
# # Amazon Q pre block. Keep at the top of this file.
# [[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh"

zsh_folder=/Users/user/.my_utils/zsh.d/

# Load Oh My Zsh configuration
source "${zsh_folder}/init/oh_my_zsh"

# Load zsh file loader
source "${zsh_folder}/init/loader"

# Load history utilities
source "${zsh_folder}/init/history_write"

# 既存の Ctrl+  を無効化(-r)
bindkey -r '^R'
bindkey -r '^S'  # incremental search

# Set colors of files
# eval $(dircolors ~/.dircolors)

# Set prompt: display current directory in blue(33) and end with $ (user) or # (root).
PS1='%F{33}%1~%f %# '

### autocomplete ###
autoload -Uz compinit && compinit
autoload -U +X bashcompinit && bashcompinit
complete -C '/usr/local/bin/aws_completer' aws

# gcloud
# source /usr/share/google-cloud-sdk/completion.zsh.inc

# Terraform
complete -o nospace -C /usr/bin/terraform terraform

# Case insensitive for completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

### BELOW ARE FOR APPLICATIONS ###

# fzf
source "${zsh_folder}/init/fzf_helper"

# NVM
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
# nvm use default >/dev/null

# autoload -Uz add-zsh-hook
# add-zsh-hook precmd set_prompt

# Set PATH for scripts
export PATH_SCRIPTS=$HOME/.my_utils/scripts

# Set PATH for npm global packages
export PATH="$HOME/.npm-global/bin:$PATH"

# [[ "$TERM_PROGRAM" == "kiro" ]] && . "$(kiro --locate-shell-integration-path zsh)"
# export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"
# export PATH="/opt/homebrew/opt/openjdk@21/bin:$PATH"

# # Amazon Q post block. Keep at the bottom of this file.
# [[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh"

# Kiro CLI post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh"
